interface AiBadgeProps {
  title?: string
  className?: string
}

export default function AiBadge({ title, className = '' }: AiBadgeProps) {
  return (
    <span
      title={title ?? 'Generated by AI from public records; not confirmed by the organization'}
      className={`border border-cool-grey text-cool-grey rounded text-[10px] px-1.5 py-0.5 font-body tracking-[0.04em] ${className}`}
    >
      AI assisted
    </span>
  )
}
