"""Generate IRS-compliant donation letters as PDF."""

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from io import BytesIO
from datetime import datetime


def generate_donation_letter(
    nonprofit_name: str,
    nonprofit_ein: str,
    donor_name: str,
    amount: int,
    donation_date: str,
    nonprofit_address: str = "Your Organization Address",
) -> bytes:
    """Generate IRS-compliant donation letter PDF.

    Args:
        nonprofit_name: Organization name
        nonprofit_ein: EIN (for IRS compliance statement)
        donor_name: Donor name or "Honored Donor" if anonymous
        amount: Donation amount in USD
        donation_date: ISO date string (YYYY-MM-DD)
        nonprofit_address: Organization mailing address

    Returns:
        PDF bytes ready to save or return to browser
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                           topMargin=0.75*inch, bottomMargin=0.75*inch,
                           leftMargin=0.75*inch, rightMargin=0.75*inch)

    story = []
    styles = getSampleStyleSheet()

    # Header
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=colors.HexColor('#1a1a1a'),
        alignment=TA_CENTER,
        spaceAfter=6,
        fontName='Helvetica-Bold'
    )
    story.append(Paragraph(nonprofit_name, header_style))

    # Subheader with address
    subheader_style = ParagraphStyle(
        'Subheader',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#666666'),
        alignment=TA_CENTER,
        spaceAfter=12
    )
    story.append(Paragraph(nonprofit_address, subheader_style))
    story.append(Spacer(1, 0.2*inch))

    # Date
    letter_style = ParagraphStyle(
        'LetterBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#1a1a1a'),
        alignment=TA_LEFT,
        spaceAfter=12
    )
    letter_date = datetime.fromisoformat(donation_date).strftime('%B %d, %Y')
    story.append(Paragraph(f"{letter_date}", letter_style))
    story.append(Spacer(1, 0.2*inch))

    # Greeting
    story.append(Paragraph(f"Dear {donor_name},", letter_style))
    story.append(Spacer(1, 0.1*inch))

    # Body
    body_text = f"""
Thank you for your generous donation of <b>${amount:,}</b> made on <b>{letter_date}</b> to {nonprofit_name}.
<br/><br/>
This letter serves as a receipt for your charitable contribution. {nonprofit_name} is a qualified charitable organization under Section 501(c)(3) of the Internal Revenue Code. Our federal tax ID (EIN) is {nonprofit_ein}.
<br/><br/>
No goods or services were provided in exchange for this contribution. Your donation is tax deductible to the extent permitted by law.
<br/><br/>
Please retain this letter for your tax records and consult with your tax advisor regarding the deductibility of this contribution.
<br/><br/>
We are deeply grateful for your support and the impact your gift will have on our mission.
"""
    story.append(Paragraph(body_text, letter_style))
    story.append(Spacer(1, 0.3*inch))

    # Closing
    story.append(Paragraph("Sincerely,", letter_style))
    story.append(Spacer(1, 0.6*inch))

    # Signature line
    sig_style = ParagraphStyle(
        'Signature',
        parent=styles['Normal'],
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#1a1a1a'),
        alignment=TA_LEFT,
        spaceAfter=12,
        borderPadding=4
    )
    story.append(Paragraph("_" * 50, sig_style))
    story.append(Paragraph(f"{nonprofit_name}<br/>Authorized Representative", sig_style))
    story.append(Spacer(1, 0.2*inch))

    # Footer with disclaimer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#999999'),
        alignment=TA_CENTER,
        spaceAfter=0,
        leading=10
    )
    story.append(Paragraph(
        "This letter was generated by Daanaa, a nonprofit discovery platform. "
        "Please verify all details before filing taxes.",
        footer_style
    ))

    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
