CREATE TABLE IF NOT EXISTS "nccs_core_2019" (
"scope" TEXT,
  "EIN" TEXT,
  "ACCNTINGFEES" TEXT,
  "ACCNTSPAYABLEEND" TEXT,
  "ACCNTSRCVBLEND" TEXT,
  "ACCPER" TEXT,
  "ACTIV1" TEXT,
  "ACTIV2" TEXT,
  "ACTIV3" TEXT,
  "ACTONBEHALFCD" TEXT,
  "ADDRESS" TEXT,
  "ADVRTPROMO" TEXT,
  "AFCD" TEXT,
  "AWAREXCESSBNFTCD" TEXT,
  "BENIFITSMEMBRS" TEXT,
  "CAPITALSTKTRSTEND" TEXT,
  "CEASEOPERATIONSCD" TEXT,
  "CENSUSTRACT" TEXT,
  "CITY" TEXT,
  "CLASSCD" TEXT,
  "COMPLTSCHOCD" TEXT,
  "COMPNSATNANDOTHR" TEXT,
  "CONDUCT5PERCENTCD" TEXT,
  "CONTACT" TEXT,
  "CONVERCONVENTMTNG" TEXT,
  "CRCOUNSELINGQSTNCD" TEXT,
  "CURRFRMRCVBLEND" TEXT,
  "DEDUCTCD" TEXT,
  "DEFEREDREVNUEND" TEXT,
  "DEPRCATNDEPLETN" TEXT,
  "DIRBUSNRELTDCD" TEXT,
  "DISTRIBTODONORCD" TEXT,
  "DNRADVISEDFUNDSCD" TEXT,
  "EFILE" TEXT,
  "ENGAGEEXCESSBNFTCD" TEXT,
  "EOSTATUS" TEXT,
  "EPOSTCARD" TEXT,
  "ESCRWACCNTLIABEND" TEXT,
  "EXCBUSHLDNGSCD" TEXT,
  "EXCEEDS1PCT509" TEXT,
  "EXCEEDS2PCT170" TEXT,
  "EXPRSTMNTCD" TEXT,
  "F1096CNT" TEXT,
  "F8282CNT" TEXT,
  "FEESFORSRVCINVSTMGMT" TEXT,
  "FEESFORSRVCLOBBY" TEXT,
  "FEESFORSRVCMGMT" TEXT,
  "FEESFORSRVCOTHR" TEXT,
  "FILEDF1098CCD" TEXT,
  "FILEDF720CD" TEXT,
  "FILEDF8282CD" TEXT,
  "FILEDF8886TCD" TEXT,
  "FILEDF8899CD" TEXT,
  "FILEDF990TCD" TEXT,
  "FILEDLIEUF1041CD" TEXT,
  "FILENAME" TEXT,
  "FILERQRDRTNSCD" TEXT,
  "FIPS" TEXT,
  "FISYR" TEXT,
  "FISYRP" TEXT,
  "FMLYBUSNRELTDCD" TEXT,
  "FNDNCD" TEXT,
  "FNDSRCVDCD" TEXT,
  "FRCD" TEXT,
  "FRGNACCTCD" TEXT,
  "FRGNAGGRAGRNTSCD" TEXT,
  "FRGNGRNTSCD" TEXT,
  "FRGNOFFICECD" TEXT,
  "FRGNREVEXPNSCD" TEXT,
  "FW2GCNT" TEXT,
  "GFTGRNTSRCVD170" TEXT,
  "GRANTOOFFICERCD" TEXT,
  "GRNSTTOINDIV" TEXT,
  "GRNTSPAYABLEEND" TEXT,
  "GRNTSTOFRGNGOVT" TEXT,
  "GRNTSTOGOVT" TEXT,
  "GRSINC170" TEXT,
  "GRSINC509" TEXT,
  "GRSINCFNDRSNG" TEXT,
  "GRSINCGAMING" TEXT,
  "GRSRCPTSACTIVITIES509" TEXT,
  "GRSRCPTSADMISSN509" TEXT,
  "GRSRCPTSPUBLICUSE" TEXT,
  "GRSRCPTSRELATED170" TEXT,
  "GRSRNTSPRSNL" TEXT,
  "GRSRNTSREAL" TEXT,
  "HLDASSETSINTERMPERMCD" TEXT,
  "HOSPAUDFINSTMTCD" TEXT,
  "INCLINFINSTMTCD" TEXT,
  "INFOTECH" TEXT,
  "INPRIOR" TEXT,
  "INPRIORSRC" TEXT,
  "INSURANCE" TEXT,
  "INTANGIBLEASSETSEND" TEXT,
  "INTERESTAMT" TEXT,
  "INTINCNTRLCD" TEXT,
  "INVNTRIESALESEND" TEXT,
  "INVSTMNTSEND" TEXT,
  "INVSTMNTSOTHREND" TEXT,
  "INVSTMNTSPRGMEND" TEXT,
  "INVSTPROCEEDSCD" TEXT,
  "LATITUDE" TEXT,
  "LBBYINGACTVTSCD" TEXT,
  "LEGALFEES" TEXT,
  "LESSDIRFNDRSNG" TEXT,
  "LESSDIRGAMING" TEXT,
  "LEVEL1" TEXT,
  "LEVEL2" TEXT,
  "LEVEL3" TEXT,
  "LEVEL4" TEXT,
  "LNDBLDGSEQUIPEND" TEXT,
  "LOANTOFFICERCD" TEXT,
  "LONGITUDE" TEXT,
  "MAINTESCRWACCNTCD" TEXT,
  "MAINTWRKOFARTCD" TEXT,
  "MAJGRPB" TEXT,
  "MANUALLY_FIXED" TEXT,
  "MISCREV11ACD" TEXT,
  "MISCREV11BCD" TEXT,
  "MISCREV11CCD" TEXT,
  "MISCREVTOT11B" TEXT,
  "MISCREVTOT11C" TEXT,
  "MISCREVTOT11D" TEXT,
  "MISCREVTOTA" TEXT,
  "MSA_NECH" TEXT,
  "NAICS" TEXT,
  "NAME" TEXT,
  "NCCSKEY" TEXT,
  "NCCSKEY2" TEXT,
  "NETGNLS" TEXT,
  "NETINCFNDRSNG" TEXT,
  "NETINCGAMING" TEXT,
  "NETINCUNRELATD509" TEXT,
  "NETINCUNRELTD170" TEXT,
  "NOCONTRACTOR100KCNT" TEXT,
  "NOEMPLYEESW3CNT" TEXT,
  "NOINDIV100KCNT" TEXT,
  "NONINTCASHEND" TEXT,
  "NOTESLOANSRCVBLEND" TEXT,
  "NOTFYDNRVALCD" TEXT,
  "NTEE1" TEXT,
  "NTEECC" TEXT,
  "NTEEFINAL" TEXT,
  "NTEEFINAL1" TEXT,
  "NTEEIRS" TEXT,
  "NTEESRC" TEXT,
  "NTMAJ10" TEXT,
  "NTMAJ12" TEXT,
  "NTMAJ5" TEXT,
  "OCCUPANCY" TEXT,
  "OFFICEXPNS" TEXT,
  "OPERATEHOSPTLCD" TEXT,
  "OPERATESCHOOLS170CD" TEXT,
  "ORGCD" TEXT,
  "ORGTRNSFRCD" TEXT,
  "OTHRASSETSEND" TEXT,
  "OTHREMPLYEEBENEF" TEXT,
  "OTHREXPNSA" TEXT,
  "OTHREXPNSB" TEXT,
  "OTHREXPNSC" TEXT,
  "OTHREXPNSD" TEXT,
  "OTHREXPNSE" TEXT,
  "OTHREXPNSF" TEXT,
  "OTHRINC170" TEXT,
  "OTHRINC509" TEXT,
  "OTHRLIABEND" TEXT,
  "OUTNCCS" TEXT,
  "OUTREAS" TEXT,
  "OWNSEPENTCD" TEXT,
  "PAIDINSURPLUSEND" TEXT,
  "PAYBLETOFFCRSEND" TEXT,
  "PENSIONPLANCONTRB" TEXT,
  "PERMRSTRCTNETASSTSEND" TEXT,
  "PLDGEGRNTRCVBLEND" TEXT,
  "PMSA" TEXT,
  "POLITICALACTVTSCD" TEXT,
  "PREMIUMSPAIDCD" TEXT,
  "PREPAIDEXPNSEND" TEXT,
  "PRGMSERVCODE2ACD" TEXT,
  "PRGMSERVCODE2BCD" TEXT,
  "PRGMSERVCODE2CCD" TEXT,
  "PRGMSERVCODE2DCD" TEXT,
  "PRGMSERVCODE2ECD" TEXT,
  "PROHIBTDTXSHLTRCD" TEXT,
  "PROVIDEGOODSCD" TEXT,
  "PRPTYINTRCVDCD" TEXT,
  "PRTYNOTIFYORGCD" TEXT,
  "PUBSUPPLESSPCT170" TEXT,
  "PUBSUPPLESUB509" TEXT,
  "PUBSUPPSUBTOT170" TEXT,
  "PUBSUPPSUBTOT509" TEXT,
  "PYMTOAFFILIATES" TEXT,
  "QUALHLTHONHND" TEXT,
  "QUALHLTHPLNCD" TEXT,
  "QUALHLTHREQMNTN" TEXT,
  "RANDNUM" TEXT,
  "RCVBLDISQUALEND" TEXT,
  "RCVDFRMDISQUALSUB509" TEXT,
  "RCVDPDTNGCD" TEXT,
  "RECVARTCD" TEXT,
  "RECVNONCASHCD" TEXT,
  "RELTDORGCD" TEXT,
  "RNTLEXPNSPRSNL" TEXT,
  "RNTLEXPNSREAL" TEXT,
  "RNTLINCPRSNL" TEXT,
  "RNTLINCREAL" TEXT,
  "ROYALTSEXPNS" TEXT,
  "ROYALTSINC" TEXT,
  "RPTGRNTSTOGOVTCD" TEXT,
  "RPTGRNTSTOINDVCD" TEXT,
  "RPTINCFNNDRSNGCD" TEXT,
  "RPTINCGAMINGCD" TEXT,
  "RPTINVSTOTHSECD" TEXT,
  "RPTINVSTPRGRELCD" TEXT,
  "RPTLNDBLDGEQPTCD" TEXT,
  "RPTOTHASSTCD" TEXT,
  "RPTOTHLIABCD" TEXT,
  "RPTPROFNDRSNGFEESCD" TEXT,
  "RPTYESTOCOMPNSTNCD" TEXT,
  "RULEDATE" TEXT,
  "S4966DISTRIBCD" TEXT,
  "S501C3OR4947A1CD" TEXT,
  "SAMEPUBSUPPSUBTOT170" TEXT,
  "SAMEPUBSUPPSUBTOT509" TEXT,
  "SCHDBIND" TEXT,
  "SEC_NAME" TEXT,
  "SELLOREXCHCD" TEXT,
  "SEPCNSLDTFINSTMTCD" TEXT,
  "SEPINDAUDFINSTMTCD" TEXT,
  "SERVASOFFICERCD" TEXT,
  "SOIYR" TEXT,
  "SOLICITCNTRBCD" TEXT,
  "SOURCE" TEXT,
  "SRVCSVAL170" TEXT,
  "SRVCSVAL509" TEXT,
  "STATE" TEXT,
  "STYEAR" TEXT,
  "SUBCD" TEXT,
  "SUBJTO6033CD" TEXT,
  "SUBSECCD" TEXT,
  "SUBTOTPUB509" TEXT,
  "SUBTOTSUPPINC509" TEXT,
  "SVNGSTEMPINVEND" TEXT,
  "TAXPER" TEXT,
  "TAXPERP" TEXT,
  "TEMPRSTRCTNETASSTSEND" TEXT,
  "TOTCOMPRELATEDE" TEXT,
  "TOTESTCOMPF" TEXT,
  "TOTGFTGRNTRCVD509" TEXT,
  "TOTNETLIABASTEND" TEXT,
  "TOTNOOFORGSCNT" TEXT,
  "TOTREPRTABLED" TEXT,
  "TOTREV2ACOLA" TEXT,
  "TOTREV2BCOLA" TEXT,
  "TOTREV2CCOLA" TEXT,
  "TOTREV2DCOLA" TEXT,
  "TOTREV2ECOLA" TEXT,
  "TOTREV2FCOLA" TEXT,
  "TOTSUPP170" TEXT,
  "TOTSUPP509" TEXT,
  "TOTSUPPORT" TEXT,
  "TRAVEL" TEXT,
  "TRAVELOFPUBLICOFFCL" TEXT,
  "TXEXMPTBNDCD" TEXT,
  "TXEXMPTBNDSPROCEEDS" TEXT,
  "TXEXMPTINT" TEXT,
  "TXREVNUELEVIED170" TEXT,
  "TXREVNUELEVIED509" TEXT,
  "UNRELTXINCLS511TX509" TEXT,
  "UNRSTRCTNETASSTSEND" TEXT,
  "UNSECUREDNOTESEND" TEXT,
  "VALIDATION_STATE" TEXT,
  "WTHLDNGRULESCD" TEXT,
  "ZIP" TEXT,
  "ZIP5" TEXT,
  "ASS_BOY" TEXT,
  "ASS_EOY" TEXT,
  "BOND_BOY" TEXT,
  "BOND_EOY" TEXT,
  "COMPENS" TEXT,
  "COMPENSP" TEXT,
  "CONT" TEXT,
  "CONTP" TEXT,
  "DIREXP" TEXT,
  "EXPS" TEXT,
  "EXPSP" TEXT,
  "FUNDBAL" TEXT,
  "FUNDFEES" TEXT,
  "FUNDFEESP" TEXT,
  "FUNDINC" TEXT,
  "FUNDINCP" TEXT,
  "GOODS" TEXT,
  "GRPROF" TEXT,
  "GRPROFP" TEXT,
  "GRREC" TEXT,
  "GRRECMEM" TEXT,
  "GRRECOTH" TEXT,
  "GRRECPUB" TEXT,
  "INITFEES" TEXT,
  "INVENTG" TEXT,
  "INVINC" TEXT,
  "INVINCP" TEXT,
  "LIAB_BOY" TEXT,
  "LIAB_EOY" TEXT,
  "MRTG_BOY" TEXT,
  "MRTG_EOY" TEXT,
  "NETA_BOY" TEXT,
  "NETINC" TEXT,
  "NETINCP" TEXT,
  "NETRENT" TEXT,
  "NETRENTP" TEXT,
  "OTHCHGS" TEXT,
  "OTHINC" TEXT,
  "OTHINCP" TEXT,
  "OTHSAL" TEXT,
  "OTHSALP" TEXT,
  "PAYTAX" TEXT,
  "PAYTAXP" TEXT,
  "PROGREV" TEXT,
  "PROGREVP" TEXT,
  "Q78A" TEXT,
  "REASON" TEXT,
  "RENTEXP" TEXT,
  "RENTINC" TEXT,
  "RETEARN" TEXT,
  "RETE_BOY" TEXT,
  "SALEOTHE" TEXT,
  "SALEOTHG" TEXT,
  "SALEOTHN" TEXT,
  "SALEOTHNP" TEXT,
  "SALESECN" TEXT,
  "SALESECNP" TEXT,
  "SALESEXP" TEXT,
  "SECUR" TEXT,
  "SPEVTG" TEXT,
  "TOTREV" TEXT,
  "TOTREV2" TEXT,
  "TOTREVP" TEXT
, total_revenue REAL);
CREATE INDEX idx_nccs_ein    ON nccs_core_2019(EIN);
CREATE INDEX idx_nccs_ntee   ON nccs_core_2019(NTEE1);
CREATE INDEX idx_nccs_state  ON nccs_core_2019(STATE);
CREATE INDEX idx_nccs_scope  ON nccs_core_2019(scope);
CREATE TABLE irs_bmf (ein TEXT PRIMARY KEY, name TEXT, ico_name TEXT, street TEXT, city TEXT, state TEXT, zip TEXT, ntee TEXT, subsection TEXT, affiliation TEXT, ruling_date TEXT, deductibility TEXT, foundation TEXT, activity TEXT, organization TEXT, status TEXT, tax_period TEXT, asset_cd TEXT, income_cd TEXT, filing_req_cd TEXT, pf_filing_req_cd TEXT, acct_pd TEXT, asset_amt REAL, income_amt REAL, revenue_amt REAL, data_date TEXT);
CREATE TABLE IF NOT EXISTS "registry_enriched"(
  EIN TEXT,
  organization_name TEXT,
  NTEE1 TEXT,
  NTEECC TEXT,
  STATE TEXT,
  CITY TEXT,
  total_revenue REAL,
  ntee1_percentile,
  state_ntee1_percentile,
  ntee1_rank,
  ntee1_total_orgs,
  source
, ntee_code TEXT, ntee_description TEXT, subseccd TEXT, have_pdfs INTEGER, website TEXT, mission TEXT, filing_object_id TEXT, latest_tax_year INTEGER, total_assets REAL, data_source TEXT DEFAULT '', updated_at TEXT, coverage_score INTEGER DEFAULT 0, deductibility TEXT, subsection TEXT, revenue_band TEXT, peer_percentile REAL, peer_rank INTEGER, peer_total INTEGER, peer_group TEXT, merit_tier TEXT, merit_score REAL, merit_band TEXT, ruling_date TEXT, accounting_period INTEGER, foundation_code INTEGER, net_assets REAL, total_expenses REAL, total_liabilities REAL, months_of_reserve REAL, zipcode TEXT, address TEXT, employee_count INTEGER, activ1 TEXT, activ2 TEXT, activ3 TEXT, program_expense_pct REAL, nccs_year INTEGER, cause_tags TEXT, is_hidden_gem INTEGER DEFAULT 0, website_status TEXT, website_checked_at TEXT, website_final_domain TEXT, donate_url TEXT, donate_platform TEXT, social_score INTEGER, social_platforms TEXT, social_checked_at TEXT, diamond_factors TEXT, donate_url_status TEXT, score_tier TEXT, donate_confidence INTEGER, donate_source_page TEXT, donate_identity_match TEXT, donate_human_review INTEGER, donate_checked_at TEXT, mission_source TEXT);
CREATE TABLE scoring_runs (
    run_id          TEXT PRIMARY KEY,
    scorer_version  TEXT NOT NULL,
    started_at      TEXT NOT NULL,
    completed_at    TEXT,
    input_file      TEXT,
    input_hash      TEXT,
    input_ein_count INTEGER,
    scorable_count  INTEGER,
    output_ein_count INTEGER,
    output_file     TEXT,
    output_hash     TEXT,
    peer_group_count INTEGER,
    score_min       REAL,
    score_max       REAL,
    score_mean      REAL,
    score_median    REAL,
    band_distribution TEXT,
    notes           TEXT,
    git_commit      TEXT
);
CREATE INDEX idx_ntee1 ON registry_enriched(NTEE1);
CREATE INDEX idx_state ON registry_enriched(STATE);
CREATE INDEX idx_revenue ON registry_enriched(total_revenue DESC);
CREATE INDEX idx_data_source ON registry_enriched(data_source);
CREATE INDEX idx_nteecc ON registry_enriched(NTEECC);
CREATE INDEX idx_percentile ON registry_enriched(ntee1_percentile DESC);
CREATE INDEX idx_name_search ON registry_enriched(organization_name COLLATE NOCASE);
CREATE INDEX idx_ein ON registry_enriched(EIN);
CREATE INDEX idx_merit_tier ON registry_enriched(merit_tier);
CREATE TABLE waitlist (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            email       TEXT NOT NULL,
            ein         TEXT,
            source      TEXT NOT NULL DEFAULT "newsletter",
            status      TEXT NOT NULL DEFAULT "new",
            notes       TEXT,
            created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX idx_merit_score ON registry_enriched(merit_score);
CREATE TABLE score_snapshots (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    EIN             TEXT    NOT NULL,
    snapshot_date   TEXT    NOT NULL,
    total_revenue   REAL,
    total_assets    REAL,
    peer_group      TEXT,
    STATE           TEXT,
    region          TEXT,
    scorer_version  TEXT    NOT NULL,
    peer_percentile REAL,
    rev_pct         REAL,
    rsv_pct         REAL,
    reserve_ratio   REAL,
    group_size      INTEGER,
    group_key       TEXT,
    UNIQUE(EIN, snapshot_date, scorer_version)
);
CREATE INDEX idx_snapshots_ein  ON score_snapshots(EIN);
CREATE INDEX idx_snapshots_date ON score_snapshots(snapshot_date);
CREATE TABLE propublica_financials (
    EIN            TEXT    NOT NULL,
    tax_prd_yr     INTEGER NOT NULL,
    totrevenue     REAL,
    totfuncexpns   REAL,
    totassetsend   REAL,
    totliabend     REAL,
    totnetassetend REAL,
    totcntrbgfts   REAL,
    totprgmrevnue  REAL,
    compnsatncurrofcr REAL,
    pdf_url        TEXT,
    PRIMARY KEY (EIN, tax_prd_yr)
);
CREATE INDEX idx_ppf_ein ON propublica_financials(EIN);
CREATE INDEX idx_ppf_yr  ON propublica_financials(tax_prd_yr);
CREATE TABLE link_feedback (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                EIN         TEXT NOT NULL,
                reason      TEXT NOT NULL,
                created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
CREATE TABLE agent_job_log (
                id           INTEGER PRIMARY KEY AUTOINCREMENT,
                agent        TEXT    NOT NULL,
                started_at   TEXT    NOT NULL,
                finished_at  TEXT,
                processed    INTEGER DEFAULT 0,
                updated      INTEGER DEFAULT 0,
                errors       INTEGER DEFAULT 0,
                llm_calls    INTEGER DEFAULT 0,
                llm_source   TEXT,
                notes        TEXT
            );
CREATE TABLE revenue_percentiles(
  EIN TEXT,
  NAME TEXT,
  scope TEXT,
  NTEE1 TEXT,
  NTEECC TEXT,
  STATE TEXT,
  CITY TEXT,
  total_revenue REAL,
  ntee1_percentile,
  state_ntee1_percentile,
  ntee1_rank,
  ntee1_total_orgs
);
CREATE INDEX idx_pct_ein ON revenue_percentiles(EIN);
CREATE INDEX idx_pct_ntee ON revenue_percentiles(NTEE1);
CREATE INDEX idx_pct_state ON revenue_percentiles(STATE);
CREATE TABLE donation_link_evidence (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    ein                   TEXT NOT NULL,
    legal_name            TEXT,
    official_website      TEXT,
    source_page           TEXT,
    candidate_url         TEXT,
    final_url             TEXT,
    processor             TEXT,
    identity_match        TEXT,
    confidence            INTEGER,
    risk_level            TEXT,
    decision              TEXT,
    public_display_allowed INTEGER DEFAULT 0,
    checked_at            TEXT,
    notes                 TEXT
);
CREATE TABLE human_review_queue (
    id                     INTEGER PRIMARY KEY AUTOINCREMENT,
    ein                    TEXT NOT NULL,
    legal_name             TEXT,
    review_reason          TEXT,
    candidate_website      TEXT,
    candidate_donation_url TEXT,
    confidence             INTEGER,
    risk_flags             TEXT,
    recommended_action     TEXT,
    created_at             TEXT,
    resolved_at            TEXT,
    resolution             TEXT
);
CREATE TABLE release_batches (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    batch_id        TEXT NOT NULL UNIQUE,
    batch_date      TEXT,
    links_reviewed  INTEGER,
    links_published INTEGER,
    links_to_review INTEGER,
    batch_status    TEXT,
    notes           TEXT
);
CREATE TABLE blocked_domains (
    domain              TEXT PRIMARY KEY,
    reason              TEXT,
    blocked_at          TEXT,
    do_not_retry_before TEXT
);
CREATE TABLE donate_work_queue (
    ein         TEXT PRIMARY KEY,
    priority    INTEGER DEFAULT 5,
    queued_at   TEXT,
    claimed_at  TEXT,
    claimed_by  TEXT,
    completed_at TEXT
);
CREATE INDEX idx_dwq_priority ON donate_work_queue(priority, queued_at)
    WHERE completed_at IS NULL;
CREATE TABLE page_cache (
    url         TEXT PRIMARY KEY,
    ein         TEXT,
    fetched_at  TEXT,
    status_code INTEGER,
    html_gz     BLOB,
    content_len INTEGER
);
CREATE INDEX idx_pc_ein ON page_cache(ein);
CREATE TABLE org_embeddings (
    ein       TEXT PRIMARY KEY,
    vector    BLOB NOT NULL,
    dim       INTEGER NOT NULL,
    text_hash TEXT,
    built_at  TEXT
);
CREATE VIRTUAL TABLE org_fts USING fts5(
                ein        UNINDEXED,
                merit_tier UNINDEXED,
                org_name,
                mission,
                city,
                state,
                tokenize = "unicode61 remove_diacritics 2"
            )
/* org_fts(ein,merit_tier,org_name,mission,city,state) */;
CREATE TABLE IF NOT EXISTS 'org_fts_data'(id INTEGER PRIMARY KEY, block BLOB);
CREATE TABLE IF NOT EXISTS 'org_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS 'org_fts_content'(id INTEGER PRIMARY KEY, c0, c1, c2, c3, c4, c5);
CREATE TABLE IF NOT EXISTS 'org_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB);
CREATE TABLE IF NOT EXISTS 'org_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID;
CREATE TABLE org_claims (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    ein              TEXT NOT NULL UNIQUE,
    email            TEXT NOT NULL,
    irs_address      TEXT NOT NULL,
    pin              TEXT NOT NULL,
    pin_expires_at   TEXT NOT NULL,
    letter_sent_at   TEXT,
    lob_letter_id    TEXT,
    claim_status     TEXT DEFAULT 'pending',
    verified_at      TEXT,
    custom_mission   TEXT,
    custom_description TEXT,
    donate_confirmed INTEGER DEFAULT 0,
    processor_auth   INTEGER DEFAULT 0,
    created_at       TEXT DEFAULT CURRENT_TIMESTAMP,
    revoked_at       TEXT,
    revoke_reason    TEXT
);
CREATE INDEX idx_org_claims_ein ON org_claims(ein);
CREATE INDEX idx_org_claims_status ON org_claims(claim_status);
CREATE INDEX idx_org_claims_pin ON org_claims(pin);
